title: Bulk Ship Hero - Mail Merge UPS / FEDEX / USPS Shipment Labels Made Easy
brand_name: BulkShipHero
header:
  title: Mail Merge Shipments
  subtitle: Upload Recipient Addresses, Download Labels or have us Mail For You!
email: sales@bulkshiphero.com
description: > # a simple web app launch site built using tachyons
url: "https://www.bulkshiphero.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:year/:month/:day/:title/
social-icons:
 - title: Facebook
   url: https://facebook.com/example
   class: facebook
 - title: Twitter
   url: https://twitter.com/blairanderson
   class: twitter
# Build settings
markdown: kramdown
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
