# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Launchr - Free Web App Landing Page Theme
launchr: Launchr - Landing page to help you showcase your new beautiful, shiny, mobile app!
ios_store_link: "#"
android_store_link: "#"
email: feedback@tachyonstemplates.com
download-link: "https://www.tachyonstemplates.com/template-overviews/tachyons-launchr/"
description: > # a simple web app launch site built using tachyons
baseurl: "/tachyons-launchr" # the subpath of your site, e.g. /blog
url: "http://www.blairanderson.co" # the base hostname & protocol for your site, e.g. http://example.com

social-icons:
 - title: Facebook
   url: https://facebook.com/example
   class: facebook
 - title: Twitter
   url: https://twitter.com/blairanderson
   class: twitter
# Build settings
markdown: kramdown
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
